{"text": "2025-07-04 23:38:28.412 | ERROR    | data_juicer.core.data.dj_dataset:337 - An error occurred during Op [image_captioning_mapper].\n", "record": {"elapsed": {"repr": "0:00:07.794597", "seconds": 7.794597}, "exception": null, "extra": {}, "file": {"name": "dj_dataset.py", "path": "/home/robot/lhp/projects/0625TCSyn/dj_synth_challenge/toolkit/data-juicer/data_juicer/core/data/dj_dataset.py"}, "function": "process", "level": {"icon": "‚ùå", "name": "ERROR", "no": 40}, "line": 337, "message": "An error occurred during Op [image_captioning_mapper].", "module": "dj_dataset", "name": "data_juicer.core.data.dj_dataset", "process": {"id": 41460, "name": "MainProcess"}, "thread": {"id": 137942923650112, "name": "MainThread"}, "time": {"repr": "2025-07-04 23:38:28.412940+08:00", "timestamp": 1751643508.41294}}}
